detectors:
  UncommunicativeParameterName:
    accept: []
    exclude: []
    enabled: true
    reject:
    - /^.$/
    - /[0-9]$/
    - /[A-Z]/
  TooManyMethods:
    max_methods: 14
    enabled: true
    exclude: []
  UncommunicativeMethodName:
    accept: []
    exclude: []
    enabled: true
    reject:
    - /^[a-z]$/
    - /[0-9]$/
    - /[A-Z]/
  LongParameterList:
    max_params: 2
    exclude:
      - "AUOM::Unit#initialize"   # 3 params
      - "AUOM::Unit#self.new"     # 3 params
      - "AUOM::Unit#self.resolve" # 3 params
    enabled: true
    overrides: {}
  FeatureEnvy:
    exclude: []
    enabled: true
  ClassVariable:
    exclude: []
    enabled: true
  BooleanParameter:
    exclude: []
    enabled: true
  IrresponsibleModule:
    exclude: []
    enabled: true
  UncommunicativeModuleName:
    accept: []
    exclude: []
    enabled: true
    reject:
    - /^.$/
    - /[0-9]$/
  NestedIterators:
    ignore_iterators: []
    exclude:
    - AUOM::Unit#initialize # 2 levels
    enabled: true
    max_allowed_nesting: 1
  TooManyStatements:
    max_statements: 6
    exclude:
      - AUOM::Inspection#pretty_unit # 7 statements
      - AUOM::Unit#initialize # 8 statements
    enabled: true
  DuplicateMethodCall:
    allow_calls: []
    exclude:
      - "AUOM::ClassMethods#new"     # invalid detection
    enabled: true
    max_calls: 1
  UtilityFunction:
    exclude: []
    enabled: true
  Attribute:
    exclude: []
    enabled: false
  UncommunicativeVariableName:
    accept: []
    exclude: []
    enabled: true
    reject:
    - /^.$/
    - /[0-9]$/
    - /[A-Z]/
  RepeatedConditional:
    enabled: true
    max_ifs: 1
  DataClump:
    exclude: []
    enabled: true
    max_copies: 1
    min_clump_size: 2
  ControlParameter:
    exclude:
      - AUOM::Unit#assert_same_unit
    enabled: true
  LongYieldList:
    max_params: 0
    exclude: []
    enabled: true
