name: CI

on: push

jobs:
  base:
    name: Base steps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Whitespace
      run: git diff --check -- HEAD~1
  ruby-spec:
    name: Specs
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle Install
      run: bundle install
    - name: Run Specs
      run: bundle exec rspec spec
  ruby-mutant-minitest:
    name: Mutant Minitest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle Install
      run: bundle install
    - name: Mutant on Minitest
      run: bundle exec mutant --include lib --require auom --use minitest -- 'AUOM*'
  ruby-mutant-rspec:
    name: Mutant RSpec
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle Install
      run: bundle install
    - name: Mutant on RSpec
      run: bundle exec mutant --include lib --require auom --use rspec -- 'AUOM*'
  ruby-rubocop:
    name: Rubocop
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle Install
      run: bundle install
    - name: Run Specs
      run: bundle exec rake metrics:rubocop
  ruby-flay:
    name: Flay
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle Install
      run: bundle install
    - name: Run Specs
      run: bundle exec rake metrics:flay
  ruby-flog:
    name: Flog
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle Install
      run: bundle install
    - name: Run Specs
      run: bundle exec rake metrics:flay
